### PR TITLE
Document MBeanServerConnection with jolokia or kubernetes

### PR DESCRIPTION
**Pull request by skarsaune**
Here is a documentation draft. Took some time to figure out the mechanics, and not sure about the outcome. 
Please have a look

### CODE REVIEW

**Comment by rhuss** [comment]
@skarsaune thanks ! Let me try to review the PR over the weekend and include the PR.

**Comment by rhuss** [comment]
Thanks a lot, the PR looks good in general.

However, I think we need some tuning wrt/ formatting and wording. Would you mind if I push some polishing updates to your branch ?

**Comment by rhuss** [comment]
I adjusted the wording a bit and cleaned up the formatting. @skarsaune please check, if this looks ok for you then we could merge.

One thing for the future: It would be cool to have a section with which options are possible when creating the connection, maybe as a table or so. The examples are a good start but I think people want to know what options are all possible. For common JSR-160 options we can refer to the official JMX documentation.

**Comment by skarsaune** [comment]
> 

Changes look great thanks. Will think about a table of options when things calm down a bit. Sorry for the late reply.

**Comment by rhuss** [comment]
cool, so lets the changes merged and I will recreate the website later today.

**Comment by rhuss** [comment]
Website has been updated

**Pull request merged**
