### PR TITLE
Always enable the BasicAuthenticationHttpContext for the JAAS authRealm

### PR DESCRIPTION
**Pull request by coheigea**
See: https://github.com/rhuss/jolokia/issues/414

### CODE REVIEW

**Comment by tcullum-rh** [comment]
@coheigea do you know the status of this PR? This was an interesting find.

**Comment by coheigea** [comment]
@tcullum-rh It's still valid, I just tested it again in Karaf. @rhuss could it be reviewed please?

**Comment by rhuss** [comment]
Sorry for the delay, but within the next three weeks I will find hopefully a slot for working on Jolokia to integrate the outstanding PRs and also create a release.

**Review by rhuss — COMMENTED** [review]
Thanks, checking again it looks good to me.

**Pull request merged**
