### PR TITLE
Fix version range in jolokia-agent-parent pom.xml

### PR DESCRIPTION
**Pull request by tokuhirom**
We want to change as expected of implementation to the specifications.
https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html.

### CODE REVIEW

**Comment by tokuhirom** [comment]
I got a same error reported for gson. ref. https://github.com/google/gson/issues/596

**Comment by rhuss** [comment]
Thanks for spotting this !

**Comment by krrrr38** [comment]
Hi, @rhuss :)

In my situation, I got following error to get jolokia-core 1.3.2 dependency.
```
Invalid JDK version in profile 'mule': Unbounded range: [1.7, for project
```
It might be fixed by this feature.

Is there any SNAPSHOT version which includes this feature?
and do you have plan to release next version?

**Comment by rhuss** [comment]
I plan to make a 1.3.3 release soon (probably at the beginning of next week).

In the meantime I just pushed a 1.3.3-SNAPSHOT so please let me know, whether this works for you.

**Comment by krrrr38** [comment]
I will use 1.3.3. Thank you for quick response!

**Pull request merged**
