### PR TITLE
Shade json-simple for JVM agent jar

### LINKED ISSUE #398: Jolokia agent affects application classloader
If application uses  com.googlecode.json-simple:json-simple:1.1.1 and jolokia is added as a javaagent, the classloader loads org.json.simple.JSONObject from jolokia bundle i.e. version 1.1.

I believe that java agents should load support classes by a special classloader so they don't affect an application, even if they brake visibility and uniqueness classloader principle.

Here  are related links:
https://javarevisited.blogspot.com/2012/12/how-classloader-works-in-java.html
https://www.voxxed.com/2015/12/class-loader-magic-how-to-write-a-java-agent

### PR DESCRIPTION
**Pull request by jerboaa**
The dependency is then included in its own namespace,
namely org.jolokia.shaded.org.json.simple*.

Closes #398

### CODE REVIEW

**Comment by jerboaa** [comment]
Thanks for the review!

**Comment by RobertRogers24** [comment]
Any update on this, we are waiting for this to be merged and released so we can utilize both json-simple and jolokia via the same Classpath.

**Comment by BernalCarlos** [comment]
Hello, any updates on this?

We're also waiting for it. Thanks.

**Comment by rhuss** [comment]
sorry, I'm late with this. Let me have a look over the weekend. Apologies for the delay ...

**Comment by rhuss** [comment]
Thanks, looks good to me ! Let's put it into a Jolokia 1.4.0, hopefully to be released soonish.

**Comment by BernalCarlos** [comment]
Thank you @rhuss !

**Pull request merged**
