### PR TITLE
Replace Travis by GitHub workflow

### LINKED ISSUE #521: Provide Continuous Integration different than Travis CI
it seems that the Travis CI configuration is no more  available. it is anyway no more very friendly with Open Source projects.

I guess the easiest is to move to GiHub Actions

### PR DESCRIPTION
**Pull request by apupier**
fixes #521

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Changes

- remove Travis and replace by GitHub Workflow
- the Sonar configuration has not been transferred but can be done in another iteration
-

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Comment by apupier** [comment]
not working yet: testing here https://github.com/apupier/jolokia/actions

**Comment by apupier** [comment]
currently this kind of error with Java 8:
https://github.com/apupier/jolokia/actions/runs/3362783605/jobs/5574971129#step:5:1970
```
Error:  t_22_signed_client_cert(org.jolokia.jvmagent.JolokiaServerTest)  Time elapsed: 0.056 s  <<< FAILURE!
javax.net.ssl.SSLException: readHandshakeRecord
	at org.jolokia.jvmagent.JolokiaServerTest.checkServer(JolokiaServerTest.java:500)
	at org.jolokia.jvmagent.JolokiaServerTest.checkServer(JolokiaServerTest.java:458)
	at org.jolokia.jvmagent.JolokiaServerTest.httpsRoundtrip(JolokiaServerTest.java:392)
	at org.jolokia.jvmagent.JolokiaServerTest.t_22_signed_client_cert(JolokiaServerTest.java:147)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at org.jolokia.jvmagent.JolokiaServerTest.checkServer(JolokiaServerTest.java:500)
	at org.jolokia.jvmagent.JolokiaServerTest.checkServer(JolokiaServerTest.java:458)
	at org.jolokia.jvmagent.JolokiaServerTest.httpsRoundtrip(JolokiaServerTest.java:392)
	at org.jolokia.jvmagent.JolokiaServerTest.t_22_signed_client_cert(JolokiaServerTest.java:147)
```

And with Java 11:
https://github.com/apupier/jolokia/actions/runs/3362783605/jobs/5574971301#step:5:1970
```
 Error:  t_22_signed_client_cert(org.jolokia.jvmagent.JolokiaServerTest)  Time elapsed: 0.134 s  <<< FAILURE!
java.net.SocketException: Broken pipe (Write failed)
	at org.jolokia.jvmagent.JolokiaServerTest.checkServer(JolokiaServerTest.java:500)
	at org.jolokia.jvmagent.JolokiaServerTest.checkServer(JolokiaServerTest.java:458)
	at org.jolokia.jvmagent.JolokiaServerTest.httpsRoundtrip(JolokiaServerTest.java:392)
	at org.jolokia.jvmagent.JolokiaServerTest.t_22_signed_client_cert(JolokiaServerTest.java:147)
```

**Comment by apupier** [comment]
I reproduce the same errors locally

**Comment by apupier** [comment]
a successful build can be seen here https://github.com/apupier/jolokia/actions/runs/3376681711

I propose to disable tests which are failing on master for now so that it can unblocks other tasks and the problem is already in master. There is a separate commit for the disabling so that we can revert it easily when starting to fix the problem. I reported https://github.com/rhuss/jolokia/issues/523
The advantage will be that at least for other modifications we will have a PR check and test for all other features which is not the case currently.

**Comment by rhuss** [comment]
@apupier happy to move this forwards, but I have very limited time to spend. What PR merge flow would you recommend?

**Comment by apupier** [comment]
I recommend using "Rebase and merge". it is keeping commit history from the Pull request and a linear history.

**Pull request merged**
