### PR TITLE
[WIP] move to JakartaEE

### LINKED ISSUE #451: Jakarta Servlet API 5.0+
The servlet API is moving to the jakarta namespace from javax.
https://jakarta.ee/specifications/servlet/5.0/

Would be great to get a release for the new namespace.

### PR DESCRIPTION
**Pull request by agebhar1**
Signed-off-by: Andreas Gebhardt <agebhar1@googlemail.com>

# Changes

- move from `javax.*` to `jakarta.*` namespace (JakartaEE 9)
- requires Eclipse Jetty at least v11 for tests, implies to run tests w/ Java 11

# TODO

- OSGI
- Mule Tests
- all comments with // TODO jakartaee

/kind api-change

Fixes #451

### CODE REVIEW

**Comment by agebhar1** [comment]
Hi @rhuss I started this PR (WIP) to start a discussion to support Jakarte Servlet 5.0 #451. I'm looking forward to hearing from you.

**Comment by rhuss** [comment]
@agebhar1 thanks for kicking off this discussion ! My first question would be how backwards compatible Servlet 5.0 is and then, how much Jolokia should support back wrt/ the Servel spec. At the moment the smallest support servlet spec is 2.5 (IIRC), and since there are still a lot of legacy installations out there we should try to keep this level as minimum bar.

Maybe we need an additional artefact for the new spec ?

**Comment by agebhar1** [comment]
Hi @rhuss thanks for taking time! Since there is a change for each class/interface from `javax.servlet.*`to `jakarta.servlet.*`, there is no backward compatibility at all (IMHO). The solution that came to my mind is to increase the main version of jolokia.

Therefore, only new installations that support Servlet API Spec 5 (JakartaEE 9) can run the new version of _Jolokia_, e.g. Eclipse Jetty >= 11 or Apache Tomcat >= 10.0.13.

What did you think?

**Comment by rhuss** [comment]
At the moment I hesitate a bit to stop the support for older Servlet Spec as there are many legacy applications still out there, and maintaining two branches for bug/security fixes is beyond what I can support (I really can work on Jolokia these days with very little investment).

So my initial idea would be to add an additional agent on the same level as `agent/war` (like e.g. `agent/war-5`). However, looking deeper into the code it looks like that the servlet dependencies goes deeper (and e.g. is also used for the osgi bundle), so this is probably not feasible.

While talking about this, Jolokia 2.0 is pending for quite a long time, but I never pushed it over the line (although it is feature-complete already and contains a nice modularization + JMX notification support). Also, I wanted to move to https://github.com/jolokia  org, but then my work focussed changed drastically (coding mostly on Knative in golang these days).  But Jolokia 2.0 would indeed be the perfect occasion for such a switch, also to increase the minimal Java version (11 then probably, maybe 8).

So yeah, increasing the major version number to 2.0 would make the most sense, but as mentioned there is tons of other stuff that I still have to rebase to the latest Jolokia developments (hopefully that does not become too hard).

And I would need a bit of time, hoping for the Christmas break (as every year :)

**Comment by agebhar1** [comment]
> So my initial idea would be to add an additional agent on the same level as agent/war (like e.g. agent/war-5). However, looking deeper into the code it looks like that the servlet dependencies goes deeper (and e.g. is also used for the osgi bundle), so this is probably not feasible.

Unfortunately not.

> [...] But Jolokia 2.0 would indeed be the perfect occasion for such a switch, also to increase the minimal Java version (11 then probably, maybe 8).

Yes, totally agree.

If you need help for pushing Jolokia towards 2.0, I should have some time during Christmas break.

For all legacy applications this repository with Jolokia 1.x still exists with the older Servlet Spec.

**Comment by jatinbindra** [comment]
> > So my initial idea would be to add an additional agent on the same level as agent/war (like e.g. agent/war-5). However, looking deeper into the code it looks like that the servlet dependencies goes deeper (and e.g. is also used for the osgi bundle), so this is probably not feasible.
> 
> Unfortunately not.
> 
> > [...] But Jolokia 2.0 would indeed be the perfect occasion for such a switch, also to increase the minimal Java version (11 then probably, maybe 8).
> 
> Yes, totally agree.
> 
> If you need help for pushing Jolokia towards 2.0, I should have some time during Christmas break.
> 
> For all legacy applications this repository with Jolokia 1.x still exists with the older Servlet Spec.

Hey agebhar1, any idea when is the Jolokia release that supports Jakarta EE will be out?
We are working on a project to include the same for JVM monitoring and was wondering if we can take a beta build (if readily  available) and do some validations around it.
Do let us know.

**Comment by agebhar1** [comment]
Hi @jatinbindra,

I've no idea but I guess @rhuss is bussy. But if he/they need help I'm glad to help.

**Comment by jatinbindra** [comment]
> At the moment I hesitate a bit to stop the support for older Servlet Spec as there are many legacy applications still out there, and maintaining two branches for bug/security fixes is beyond what I can support (I really can work on Jolokia these days with very little investment).
> 
> So my initial idea would be to add an additional agent on the same level as `agent/war` (like e.g. `agent/war-5`). However, looking deeper into the code it looks like that the servlet dependencies goes deeper (and e.g. is also used for the osgi bundle), so this is probably not feasible.
> 
> While talking about this, Jolokia 2.0 is pending for quite a long time, but I never pushed it over the line (although it is feature-complete already and contains a nice modularization + JMX notification support). Also, I wanted to move to https://github.com/jolokia org, but then my work focussed changed drastically (coding mostly on Knative in golang these days). But Jolokia 2.0 would indeed be the perfect occasion for such a switch, also to increase the minimal Java version (11 then probably, maybe 8).
> 
> So yeah, increasing the major version number to 2.0 would make the most sense, but as mentioned there is tons of other stuff that I still have to rebase to the latest Jolokia developments (hopefully that does not become too hard).
> 
> And I would need a bit of time, hoping for the Christmas break (as every year :)

Hey @rhuss , any idea when is the Jolokia release that supports Jakarta EE will be out?
We are working on a project to include the same for JVM monitoring and was wondering if we can take a beta build (if readily available) and do some validations around it.
Do let us know the time lines around it. If a beta is available, please share it with me and I will be really happy.

**Comment by mazze5** [comment]
Hi,
we moved from tomact9 to 10 and run into the same problem with JakartaEE. It would be great if jolokia would support this.
As @agebhar1 already said if we can support you @rhuss let us know.

**Comment by rhuss** [comment]
Sorry for the delay. My issue is not so much technical for now, but how I could still support Java 8 (at the moment the project won't compile with Java 8 anymore, see the tests). 

Any ideas ? (see also my latest comments from end of last year)

**Comment by mazze5** [comment]
Ok I see. Seems to be a problem with jetty server that needs java11. 
If its possible use tomcat-embedded instead of jetty for the tests. Version 10.0.x supports servlet 5.0(jakarta) and 8 and later so maybe this is an option?
But that does not solve your mentioned issue with osgi...  So I agree with you that major version change to 2.0 and then support java11+ is in my opinion the right way. If its to hard to rebase your prepared 2.0-changes, maybe first version of 2.0 make change to jakarta and java11 and in a next step integrate your new features in 2.1.

**Comment by agebhar1** [comment]
I can spent some time on the weekend to have a look at the embedded Tomcat to replace Jetty to keep Java 8. But as already mentioned, OSGI is still a problem. Maybe it could be initially dropped and added again when it's ready.

Are there any concerns about the minimum Java 11 for Version 2 of Jolokia?

**Comment by mazze5** [comment]
> I can spent some time on the weekend to have a look at the embedded Tomcat to replace Jetty to keep Java 8. But as already mentioned, OSGI is still a problem. Maybe it could be initially dropped and added again when it's ready.

That sounds good. I hope you can get it runnig with embedded Tomcat.

> Are there any concerns about the minimum Java 11 for Version 2 of Jolokia?

Not from my point of view. The Support of Java8 ends in 2025. So I think for version 2.0 its the right way to use Java11 as minimum.

**Comment by agebhar1** [comment]
Good morning. I've managed to run [Apache Tomcat 10 embedded](https://github.com/agebhar1/tomcat-10-embedded) also w/ basic HTTP authentication. The minimum required Java version is 8 as it is for Tomcat itself. In contrast to the current implementation the port for testing is obtained by the OS (port 0).

@rhuss what did you think about replacing Jetty by Tomcat to keep Java 8 as minimum version?

**Comment by mazze-5** [comment]
@rhuss hope you had a relaxing vacation. Are there any news about this concern?

**Comment by rhuss** [comment]
@agebhar1 thanks! Sorry, still quite busy with tons of other stuff. +1 for replacing Jetty with Tomcat to keep Java 8, but this does not solve our backward compatibility issue. To be realistic, Jolokia 2.0 is nothing I can tackle this year, so we might be left with the option to introduce a new module for a second servlet-based installation and skip updating the OSGi bundles (not sure how much OSGi is used these days for server-side Java).

So we would move `war` to `war-legacy` and `war-unsecured` to `war-legacy-unsecured` and then introduce a `war` for the Servlet 5.0 implementation (and maybe a `war-unsecured` for the war file without any authentication enabled). 

Wdyt, would this work ?

**Comment by agebhar1** [comment]
@rhuss, don't worry. It's exactly the same with me. I'm going on holiday in a week for a fortnight and then on a business trip.

To get the code for `javax.servlet.*`, we also need to add a 'core-legacy' package, as the `AgentServlet` uses it. These files import `javax.servlet.*`:

```
agent/core/src/main/java/org/jolokia/http/AgentServlet.java
agent/core/src/main/java/org/jolokia/util/AuthorizationHeaderParser.java
agent/core/src/test/java/org/jolokia/http/AgentServletTest.java
agent/jvm/src/test/java/org/jolokia/jvmagent/security/DelegatingAuthenticatorTest.java
agent/osgi/src/main/java/org/jolokia/osgi/JolokiaActivator.java
agent/osgi/src/main/java/org/jolokia/osgi/security/Authenticator.java
agent/osgi/src/main/java/org/jolokia/osgi/security/BaseAuthenticator.java
agent/osgi/src/main/java/org/jolokia/osgi/security/BasicAuthenticationHttpContext.java
agent/osgi/src/main/java/org/jolokia/osgi/security/BasicAuthenticator.java
agent/osgi/src/main/java/org/jolokia/osgi/security/DefaultHttpContext.java
agent/osgi/src/main/java/org/jolokia/osgi/security/JaasAuthenticator.java
agent/osgi/src/main/java/org/jolokia/osgi/security/ServiceAuthenticationHttpContext.java
agent/osgi/src/main/java/org/jolokia/osgi/servlet/JolokiaServlet.java
agent/osgi/src/test/java/org/jolokia/osgi/JolokiaActivatorTest.java
agent/osgi/src/test/java/org/jolokia/osgi/security/BasicAuthenticationHttpContextTest.java
agent/osgi/src/test/java/org/jolokia/osgi/security/JaasAuthenticatorTest.java
agent/osgi/src/test/java/org/jolokia/osgi/security/ServiceAuthenticationHttpContextTest.java
agent/osgi/src/test/java/org/jolokia/osgi/servlet/JolokiaServletTest.java
client/javascript/test-app/src/main/java/org/jolokia/it/servlet/TestMBeanRegisteringServlet.java
it/war/src/main/java/org/jolokia/it/servlet/TestMBeanRegisteringServlet.java
tools/test-util/src/main/java/org/jolokia/test/util/HttpTestUtil.java
```
Instead of `*-legacy` maybe `*-servlet4` could also be possible. At the moment I think this can work.

Another option is to switch to version 2.0 for the change to JakartaEE and to version 3.0 for the code changes already made and the minimum required Java version.

Wdyt?

**Comment by agebhar1** [comment]
Hi @rhuss hope you're doing well.

I didn't had the time to continue with the implementation during summer. Recently Apache Tomcat 10.1 dropped the support for Java 8 (see also failing [tests)](https://github.com/agebhar1/tomcat-10-embedded/actions/runs/3133185485) and requires at least version 11. For the tests itself the Java version can be different to the one used in the package.

Wdyt?

**Comment by rhuss** [comment]
Sorry for being so late; I was completely eaten up by other work since the summer (we are writing a second edition of the Kubernetes Patterns book), and I'm afraid that won't change until the end of the year. I will try to find a solution to this.

**Comment by agebhar1** [comment]
No worries @rhuss. What came to my mind is that it should be enough to add an `AgentServletJakarta` class with the Jakarta packages in `core` and add a `war-jakarta` Module.

**Comment by agebhar1** [comment]
So we can bring back Jolokia to the upcoming Spring Boot 3.

**Comment by nhmarujo** [comment]
Hi. Any news on this one? 🙂

**Comment by agebhar1** [comment]
I'm waiting for a response from @rhuss to keep going on :)

**Comment by nhmarujo** [comment]
Thanks for the fast reply @agebhar1 . Sorry, but I can't really understand the underlying problem, is it about Tomcat dropping Java 8?

With Spring Boot 3 available, would be good to see this moving forward and have Spring managing Jolokia again (was dropped recently) 🙂

**Comment by agebhar1** [comment]
As far as I can remember and understood the Java baseline should be kept by Java 8. Using the JakartaEE requires as least Java 11. I've started with replacing all `javax.servlet.*` packages by `jakarta.servlet*` which is heavy and drops OSGI and Java 8 at the moment. So I came up with the idea to add a new JakartaEE compatible module in https://github.com/rhuss/jolokia/pull/484#issuecomment-1321174144. This single module can be compiled with Java 11 and keeps all other modules as is.

**Comment by nhmarujo** [comment]
Thank you for the details @agebhar1

**Comment by rhuss** [comment]
Sorry folks, for the long delay. 'hope things will be a bit more relaxed in the new year (but I've said already several times). I I probably can't do much coding, but I think we still can proceed with the suggestion from https://github.com/rhuss/jolokia/pull/484#issuecomment-1199129781

Maybe we can keep both the `javax.` and `jakarta.` servlets in `core` with the different parts as runtime dependencies ? (but then both would need to be able to be compiled with Java 8 until now).

Still I would love to have the jakarta part in a "war" module and then maybe add an "war-servlet4" module for the older servlets. "osgi" then still just would use the dependency on "war-servlet4".

I think this would be the minimal possible solution, that does not sound too bad. wdyt ?

**Comment by ftrossbach** [comment]
Hi,
I've come across this issue and figured I'd have a go in https://github.com/rhuss/jolokia/pull/540. I hope I'm not stepping on anybodies toes and am happy for feedback. This thread has been most helpful.

**Comment by agebhar1** [comment]
Hi @ftrossbach,

this is more or less what I wanted to do in one of the next weeks. Nevertheless, well done! Don't forget, Spring Boot 3 requires JakartaEE 9.

**Comment by grgrzybek** [comment]
Sorry for being late to the party, but here is OSGi spec related issue: osgi/osgi#551

The problem is that Jolokia uses (unchanged for 12 years, available since initial commit) medieval (if not ancient) HttpService API: https://github.com/rhuss/jolokia/blame/v1.7.2/agent/osgi/src/main/java/org/jolokia/osgi/JolokiaActivator.java#L322-L325

In coming days (I hope it will be in January) I'll check the OSGi bits of Jolokia and see what can be done.

**Comment by ftrossbach** [comment]
> Don't forget, Spring Boot 3 requires JakartaEE 9.

Hi @agebhar1 , I'm unfortunately not really up-to-date on Spring as my work is currently WildFly based. I looks to me like the `jvm-spring` module doesn't itself have any JavaEE dependencies that would need to be migrated. It depends on `jvm` which has some dependencies in `DelegatingAuthenticatorTest`, but only there. Could you give me some pointers to what would need to be changed to support Spring Boot 3?

**Comment by agebhar1** [comment]
I was wrong @ftrossbach  it works fine with your branch:

```java
package com.example.demo;

import org.jolokia.http.AgentServlet;
import org.springframework.boot.actuate.endpoint.web.EndpointServlet;
import org.springframework.boot.actuate.endpoint.web.annotation.ServletEndpoint;

import java.util.Map;
import java.util.function.Supplier;

@ServletEndpoint(id = "jolokia")
public class JolokiaEndpoint implements Supplier<EndpointServlet> {
    @Override
    public EndpointServlet get() {
        return new EndpointServlet(AgentServlet.class).withInitParameters(Map.of());
    }
}
```
```java
package com.example.demo;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration(proxyBeanMethods = false)
public class JolokiaEndpointAutoConfiguration {

    @Bean
    public JolokiaEndpoint jolokiaEndpoint() {
        return new JolokiaEndpoint();
    }

}
```
```yaml
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - jolokia
```
Gives
```sh
$ http :8080/actuator/jolokia
HTTP/1.1 200 
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/plain;charset=utf-8
Date: Tue, 10 Jan 2023 18:54:44 GMT
Expires: Tue, 10 Jan 2023 17:54:44 GMT
Keep-Alive: timeout=60
Pragma: no-cache
Transfer-Encoding: chunked

{
    "request": {
        "type": "version"
    },
    "status": 200,
    "timestamp": 1673376884,
    "value": {
        "agent": "1.7.2",
        "config": {
            "agentContext": "/jolokia",
            "agentId": "192.168.1.146-79362-2d3e0b-servlet",
            "agentType": "servlet",
            "allowDnsReverseLookup": "true",
            "allowErrorDetails": "true",
            "authIgnoreCerts": "false",
            "authMatch": "any",
            "authMode": "basic",
            "canonicalNaming": "true",
            "debug": "false",
            "debugMaxEntries": "100",
            "dispatcherClasses": "org.jolokia.http.Jsr160ProxyNotEnabledByDefaultAnymoreDispatcher",
            "historyMaxEntries": "10",
            "includeStackTrace": "true",
            "listenForHttpService": "true",
            "mimeType": "text/plain",
            "multicastGroup": "239.192.48.84",
            "multicastPort": "24884",
            "policyLocation": "classpath:/jolokia-access.xml",
            "realm": "jolokia",
            "serializeException": "false",
            "streaming": "true",
            "useRestrictorService": "false"
        },
        "info": {},
        "protocol": "7.2"
    }
}
```

**Comment by vanta** [comment]
Any update here on this PR?

**Comment by agebhar1** [comment]
I close this PR in favor of #540.

**Comment by grgrzybek** [comment]
I'd like to add final comment to this issue. I'll definitely look at #540 and continue the discussion/plans under another issue: #451

The reason is that I've volunteered to review `2.0` branch, ensure that it contains the same (and some extra, because it's 2.0) functionality as current `main` branch (Jolokia 1.x) with the bold goal to release Jolokia 2.0 somewhere in October 2023.

@rhuss did a great job restructuring Jolokia code in 2.0 and keeping it (for most of the time ;)) in sync with main branch. I've polished few things (because merges with main branch stopped at some point), fixed quite some tests etc.

Summarizing the current situation (which I'll elaborate on under #451), I'm working on making `jolokia-server-core` completely independent on Servlet API version used and move Servlet API specific interfaces/classes to two sets of modules:
* with `servlet` suffix (roughly) - these modules will accompany the Servlet API agnostic modules to provide `jakarta.servlet` implementations
* with `servlet-ee8` suffix (roughly) - these modules will accompany the Servlet API agnostic modules to provide `javax.servlet` implementations

The `ee8` quialifier/classifier is inspired by what Jetty team did to Jetty 12. But you can change the decision if there are valid arguments ;).

The ambitious goal is to keep Jolokia 2.0 (@rhuss I've just realized it today) basically JDK8 friendly with the exceptions of `jakarta.servlet` dependent modules, which could be JDK11+. That's at first glance - but there's a chance we can keep JDK8 baseline across entire Jolokia 2.0 (thanks to Tomcat, because version 10.x is already based on JakartaEE 9, but keeps JDK8 compatibility. Jetty 11+ and Undertow 2.3+ are JDK11+).

So please watch #451 for the updates ;)

**Comment by grgrzybek** [comment]
After some thinking, Jolokia 2.0 will not add extra `-servlet` and `-servlet-ee8` modules and entire Jolokia will be compatible with JakartaEE9+ (`jakarta.servlet` package _only_.

For some time, Jolokia 1.x will be supported for users of JakartaEE8 and JDK1.6 - 1.8).

**Pull request closed without merging**
